name: Update Github Issue and Pull Request
description: Prefixes the PR title with a Jira issue key, adds the Jira key and the issue key to the body if not present, and also assign the issue to PR author.

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH
        (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH
  
    - name: Check Issues Are Disabled
      shell: pwsh
      id: check-issues-are-disabled
      run: | 
        $message = $(gh issue list --repo '${{ github.repository }}')
        echo $message

    - name: Add Jira Issue Code to Pull Request
      # If this is run for a PR opened from a fork (not from a branch in the given repo) then "Resource not accessible
      # by integration" errors can happen. Thus, not running it for forks during the pull_request event (but it can
      # run during push, for example). See https://github.com/Lombiq/GitHub-Actions/issues/72 for details.
      if: github.event.pull_request == '' || github.event.pull_request.head.repo.fork == false
      shell: pwsh
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_BODY: ${{ github.event.pull_request.body }}
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      run: |
        $params = @{
            JiraBaseUrl = $Env:JIRA_BASE_URL ? $Env:JIRA_BASE_URL : "https://lombiq.atlassian.net"
            GitHubRepository = $Env:GITHUB_REPOSITORY
            Branch = $Env:GITHUB_HEAD_REF
            Title = $Env:PR_TITLE
            Body = $Env:PR_BODY
            Assignee = "${{ env.PR_AUTHOR }}"
            PullRequestID = ${{ github.event.number }}
        }
        Update-GitHubIssueAndPullRequest @params
