name: Tune Windows performance
description: >
  Employs various tricks to increase build performance under Windows. Add this as the very first step in your workflow.

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH

    - name: Initialize ext4 Drive
      shell: pwsh
      run: Initialize-Ext4Drive
