name: Check Issues Are Disabled
description: Checks whether the current repository has disabled the issues feature.

outputs:
  issues-disabled:
    description: Whether the issues are disabled or not.
    value: ${{ steps.repository-has-disabled-issues.outputs.issues-disabled }}

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH
        (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH
  
    - name: Check Issues Are Disabled In Current Repository
      shell: pwsh
      id: repository-has-disabled-issues
      run: |
        $issueResponse = $(gh issue list --repo '${{ github.repository }}')
        $issuesAreDisabled = "$issueResponse" -eq $null
        Set-GitHubOutput 'issues-disabled' $issuesAreDisabled
