name: Check Issues Are Disabled
description: Checks whether the current repository has disabled the issues feature.

outputs:
  issues-disabled:
    description: Returns 'true' or 'false' indicating whether the issues feature is disabled.
    value: ${{ steps.repository-has-disabled-issues.outputs.issues-disabled }}

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH
        (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH
  
    - name: Check Issues are Disabled in Current Repository
      shell: pwsh
      id: repository-has-disabled-issues
      run: |
        $issueResponse = $null
        
        try {
          $issueResponse = $(gh issue list --repo '${{ github.repository }}')
        } catch {
          Write-Host "Error while using gh cli"
        }
        
        Write-Host "Issue Response: $issueResponse"
        $issuesAreDisabled = "$issueResponse" -eq $null
        Write-Host "Boolean result: $issuesAreDisabled"
        Set-GitHubOutput 'issues-disabled' $issuesAreDisabled
        Write-Host "Post GithubOutput"
