name: Check Issues Are Disabled
description: Checks whether the current repository has disabled the issues feature.

outputs:
  issues-disabled:
    description: Returns 'true' or 'false' indicating whether the issues feature is disabled.
    value: ${{ steps.repository-has-disabled-issues.outputs.issues-disabled }}

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH
        (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH

    - name: Check Issues are Disabled in Current Repository
      shell: pwsh
      id: repository-has-disabled-issues
      run: |
        $repoInfo = Invoke-RestMethod `
        -Uri "https://api.github.com/repos/${{ github.repository }}" `
        -Headers @{Authorization = "token $env:GITUB_TOKEN"}
        
        if ($repoInfo.has_issues) {
          Write-Output "Issues are enabled for this repository."
        } else {
          Write-Output "Issues are disabled for this repository."
        }
        try {
          $ErrorActionPreference = 'Continue'
          echo $ErrorActionPreference
          $output = gh issue status --repo '${{ github.repository }}'
          $issuesAreDisabled = ($output -eq $null)
        }
        catch [System.Exception] {
          Write-Host "Caught an error"
          Write-Host $_.Exception.Message
        }
        Write-Host "Boolean result: $issuesAreDisabled"
        Set-GitHubOutput 'issues-disabled' $issuesAreDisabled
        
