name: Check Issues Are Disabled
description: Checks whether the current repository has disabled the issues feature.

outputs:
  issues-disabled:
    description: Returns 'true' or 'false' indicating whether the issues feature is disabled.
    value: ${{ steps.repository-has-disabled-issues.outputs.issues-disabled }}

runs:
  using: "composite"
  steps:
    - name: Check Issues are Disabled in Current Repository
      shell: bash
      id: repository-has-disabled-issues
      run: |
        issues_status=$(gh issue status --repo "${{ github.repository }}" 2>&1)
        if [[ $issues_status == *"GraphQL error"* ]]; then
          issuesAreDisabled=true
        else
          issuesAreDisabled=false
        fi
        echo "$issuesAreDisabled"
        echo "issues-disabled=$issuesAreDisabled" >> $GITHUB_ENV
        echo "issues-disabled=$issuesAreDisabled" >> $GITHUB_OUTPUT
