name: YAML Linting
description: Runs a linter on YAML files.


inputs:
  config-file-path:
    description: 'Path to the yamllint configuration file'
    required: true
    default: '.yamllint.yaml'

  search-path:
    description: 'Path to search for YAML files'
    required: true
    default: '.'

runs:
  using: "composite"
  steps:
    # - name: Run yamllint on Linux
    #   if: ${{ runner.os == 'Linux' }}
    #   run: yamllint -c "${{ github.action_path }}/../../../.trunk/configs/.yamllint.yaml" .
    #   shell: bash

    - name: Run yamllint on Windows
      if: ${{ runner.os == 'Windows' }}
      run: yamllint -c "${{ inputs.config-file-path }}" "${{ inputs.search-path }}"
      shell: pwsh
