name: Check Issues Are Enabled
description: Checks whether the current repository has the issues feature enabled.

outputs:
  issues-enabled:
    description: Returns 'true' or 'false' indicating whether the issues feature is enabled.
    value: ${{ steps.repository-has-enabled-issues.outputs.issues-enabled }}

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH
        (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH

    - name: Check Issues are Enabled in Current Repository
      shell: pwsh
      id: repository-has-enabled-issues
      run: |
        $issuesAreEnabled = $(gh api repos/${{ github.repository }} | ConvertFrom-Json).has_issues
        Set-GitHubOutput 'issues-enabled' $issuesAreEnabled
        
