name: Verify that .NET packages are consolidated
description: >
  Verifies that the NuGet packages of a .NET solution are consolidated, i.e. the same version of a given package is used
  in all projects.

inputs:
  directory:
    required: false
    default: .
    description: Path to the directory where a solution file can be found.
  solution-path:
    required: false
    default: "*.sln"
    description: >
      The path of the solution file to be processed. The value is given to PowerShell's `Get-ChildItem` cmdlet as-is, so
      grepping is still possible but a name with spaces must be escaped separately.

runs:
  using: "composite"
  steps:
    - name: Setup
      shell: pwsh
      run: dotnet tool install dotnet-consolidate --global --version 2.0.0
    - name: Verify consolidation status
      shell: pwsh
      working-directory: ${{ inputs.directory }}
      run: dotnet consolidate -s (Get-ChildItem ${{ inputs.solution-path }}).FullName
