name: Check For Merge Conflict
description: Checks for merge conflicts in the current pull request.

runs:
  using: "composite"
  steps:
    - name: Check for merge conflict
      if: github.event.pull_request == '' || github.event.pull_request.head.repo.fork == false
      # releases/2.1.0
      uses: eps1lon/actions-label-merge-conflict@92924ba33a60e436034b0ac3838de523bf7df071
      with:
        repoToken: ${{ env.GITHUB_TOKEN }}
        commentOnDirty: "This pull request has merge conflicts. Please resolve those before requesting a review."
        dirtyLabel: "Merge Conflict"
