name: Check current workflow is the latest workflow
description: Checks whether the current workflow is the most recent workflow.

inputs:
  current-workflow-id:
    description: The current workflow run's database id.
    required: true
    default: ""

outputs:
  should-run:
    description: The latest workflow run's database id.
    value: ${{ steps.check-current-workflow-equals-latest.outputs.should-run }}

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH
        (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH
      
    - name: Check Current Workflow Equals Latest
      shell: pwsh
      id: check-current-workflow-equals-latest
      run: |
        $latestWorkflowRunNumber=$(gh run list --limit 1 --json databaseId | jq -r '.[0].databaseId')
        echo "Latest Workflow Run Number: $latestWorkflowRunNumber"
        $currentEqualsLatest= ($latestWorkflowRunNumber -eq ${{ inputs.current-workflow-id }})
        Set-GitHubOutput -Key 'should-run' -Value $currentEqualsLatest
