# Intentionally not documented in Actions.md since it's only meant for internal use
name: Check Current Workflow Is The Latest Workflow
description: Checks whether the current workflow is the most recent workflow for the pull request.

inputs:
  current-workflow-id:
    description: The current workflow run's database id.
    required: true
    default: ""

outputs:
  should-run:
    description: Whether subsequent jobs should run.
    value: ${{ steps.check-current-workflow-equals-latest.outputs.should-run }}

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH
      
    - name: Check Current Workflow Equals Latest
      shell: pwsh
      id: check-current-workflow-equals-latest
      run: |
        $latestWorkflowRunJson = $(gh run list --limit 1 --json databaseId | ConvertFrom-Json)
        echo "TEST=$latestWorkflowRunJson"
        $latestWorkflowRunNumber = $latestWorkflowRunJson[0].databaseId
        $currentEqualsLatest = ($latestWorkflowRunNumber -eq ${{ inputs.current-workflow-id }})
        Set-GitHubOutput 'should-run' $currentEqualsLatest
