name: Run .NET tests
description: >
  Runs .NET unit and UI tests (with the Lombiq UI Testing Toolbox for Orchard Core:
  https://github.com/Lombiq/UI-Testing-Toolbox), generates a test report and uploads UI testing failure dumps to
  artifacts.

inputs:
  build-directory:
    required: false
    default: .
    description: Path to the directory where a solution file can be found and thus the .NET build has run.
  test-verbosity:
    required: false
    default: quiet
    description: Verbosity parameter for dotnet test.
  ui-test-parallelism:
    required: false
    default: "-1"
    description: >
      Determines how many UI tests will run in parallel. Affects both xUnit's maxParallelThreads configuration and the
      MaxParallelTests configuration of Lombiq UI Testing Toolbox. If set to "-1" then the configuration coming from the
      code won't be overridden.

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH

    - name: Setup & Set UI Test Parallelization
      shell: pwsh
      run: |
        if (${{ inputs.ui-test-parallelism }} -eq -1)
        {
            Write-Output "The UI test parallelism configuration isn't overridden."
            Exit 0
        }

        "Lombiq_Tests_UI__OrchardCoreUITestExecutorConfiguration__MaxParallelTests=${{ inputs.ui-test-parallelism }}" >> $Env:GITHUB_ENV

        Set-XUnitMaxParallelThreads -MaxParallelThreads ${{ inputs.ui-test-parallelism }}
    
    - name: Run Tests
      shell: pwsh
      working-directory: ${{ inputs.build-directory }}
      run: Invoke-SolutionTests -Verbosity ${{ inputs.test-verbosity }}

    # Note that uploading the failure dumps would fail under Windows if the path were too long, regardless of
    # LongPathsEnabled, see: https://github.com/actions/upload-artifact/issues/309. To get around that we merge all
    # FailureDumps into the solution root.
    # FailureDump handling should also happen when the build is canceled, which is especially important if this happens
    # due to timeout.
    - name: Merge FailureDumps
      shell: pwsh
      if: hashFiles(format('{0}/test/**/FailureDumps', inputs.build-directory))
      run: Merge-FailureDumps -Directory "${{ inputs.build-directory }}"

    - name: Upload UI testing artifacts
      uses: actions/upload-artifact@v3
      # We don't need additional conditions, because of the "if-no-files-found" setting.
      if: always()
      with:
        name: ui-test-failure-dump-${{ inputs.build-directory }}-${{ matrix.machine-type }}
        path: |
          ${{ inputs.build-directory }}/FailureDumps/
          test.out
        if-no-files-found: ignore

    - name: Test Report
      # v8
      uses: phoenix-actions/test-reporting@1e9b578818d03d6df50ce8e60d024a000bf3ab63
      if: always()
      with:
        name: Test Results (${{inputs.build-directory}}|${{ matrix.machine-type }})
        path: '${{inputs.build-directory}}/**/*.trx'
        reporter: dotnet-trx
        fail-on-error: 'false'
    - name: Always test
      if: always()
      shell: pwsh
      run: |
        Write-Output "Did this work? $(Get-Date)"
