name: Set up .NET
description: Sets up the .NET SDK.

inputs:
  dotnet-version:
    required: false
    default: 6.0.x
    description: Version of the .NET SDK to set up.

runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      shell: pwsh
      run: |
        # This ceremony is needed to make the env vars available in subsequent steps too, see:
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable.
        # Note that in PowerShell, somehow an echo is not needed. Be sure not to put spaces around the equal signs when
        # writing to $Env:GITHUB_ENV.
        "DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true" >> $Env:GITHUB_ENV
        $Env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

        "DOTNET_CLI_TELEMETRY_OPTOUT=true" >> $Env:GITHUB_ENV
        $Env:DOTNET_CLI_TELEMETRY_OPTOUT = "true"

    # setup-dotnet won't install a version if it is already preinstalled on the VM. Note that it checks the latest
    # released .NET version for wildcard versions. So, e.g. with 6.0.x specified it'll still install 6.0.402 if the VM
    # only has 6.0.401. See: https://github.com/actions/setup-dotnet/issues/356.
    - name: Set up .NET
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
