name: Markdown Linting

on:
  workflow_call:
    secrets:
      CHECKOUT_TOKEN:
        required: false
        description: >
          The GitHub token to authenticate checkout. Pass in a GitHub personal access token if authenticated submodules
          are used.

    # When updating defaults here also update them in the `markdown-lint` action.
    inputs:
      cancel-workflow-on-failure:
        description: When set to "true", it will cancel the current workflow run with all jobs if this workflow fails.
        type: string
        default: 'true'
      config:
        description: Path to a file to use for the base configuration object (defaults to "lombiq.markdownlint.json").
        type: string
        default: '.github/actions/markdown-lint/lombiq.markdownlint.json'
      fix:
        description: Whether to fix issues automatically for the rules that support it (any truthy value enables).
        type: string
        default: ''
      globs:
        description: Glob expression(s) of files to lint (newline-delimited).
        type: string
        default: '**/*.{md,markdown}'
      separator:
        description: String to use as a separator for the "globs" input (defaults to newline).
        type: string
        default: "\n"
      timeout-minutes:
        type: number
        default: 1
        description: Configuration for the timeout-minutes parameter of the workflow.

jobs:
  markdown-linting:
    name: Markdown Linting
    runs-on: ubuntu-22.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Markdown Linting
        uses: Lombiq/GitHub-Actions/.github/actions/markdown-lint@issue/OSOE-744
        with:
          config: ${{ inputs.config }}
          fix: ${{ inputs.fix }}
          globs: ${{ inputs.globs }}
          separator: ${{ inputs.separator }}

      - name: Setup Scripts
        shell: pwsh
        run: |
          "${{ github.action_path }}" >> $Env:GITHUB_PATH
          (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH

      - name: List files updated by markdown-lint automatic fixes
        if: inputs.fix == 'true'
        id: markdown-lint-fix-files
        run: |
          $files = ConvertFrom-MultiLineStringToStringArray -Lines (git diff --name-only '*.md' '*.markdown')
          Set-GitHubOutput 'files' $files

      - name: Upload files fixed by markdown-lint
        uses: Lombiq/GitHub-Actions/.github/actions/upload-artifact@dev
        if: inputs.fix == 'true' && steps.markdown-lint-fix-files.outputs.files != ''
        with:
          name: markdown-lint-fixed-files
          path: steps.markdown-lint-fix-files.outputs.files
          if-no-files-found: warn
          retention-days: 1

      - name: Fail workflow if markdown-lint fixes were made
        if: inputs.fix == 'true' && steps.markdown-lint-fix-files.outputs.files != ''
        run: exit 1

      - name: Cancel Workflow on Failure
        if: failure() && inputs.cancel-workflow-on-failure == 'true'
        uses: Lombiq/GitHub-Actions/.github/actions/cancel-workflow@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
