name: Markdown Linting

concurrency:
  # If "cancel-in-progress-for-this-pr" is set to "true" and this is running for a pull request, then the concurrency
  # key will be constructed from the name of the workflow and the branch name, causing the already running job in this
  # workflow for this pull request to be cancelled. Otherwise it will be the ID of the workflow run, making it globally
  # unique and not cancel anything. Concurrency is defined for the whole workflow, because it has only one job. A
  # technical name for this workflow is also included in both cases, so that it doesn't come into conflict with other
  # jobs calling a different workflow that are started by the same caller workflow.
  group: |
    ${{
      inputs.cancel-in-progress-for-this-pr == 'true' && github.event_name == 'pull_request'
        && format('{0}_markdown-lint_{1}', github.workflow, github.ref)
        || format('{0}_markdown-lint', github.run_id)
    }}
  cancel-in-progress: ${{ inputs.cancel-in-progress-for-this-pr == 'true' }}

on:
  workflow_call:
    secrets:
      CHECKOUT_TOKEN:
        required: false
        description: >
          The GitHub token to authenticate checkout. Pass in a GitHub personal access token if authenticated submodules
          are used.

    # When updating defaults here also update them in the `markdown-lint` action.
    inputs:
      cancel-in-progress-for-this-pr:
        description: >
          When set to "true", it will cancel the already running workflow for this pull request. See the concurrency
          settings of the workflow above for more details.
        type: string
        default: 'true'
      cancel-workflow-on-failure:
        description: When set to "true", it will cancel the current workflow run with all jobs if this workflow fails.
        type: string
        default: 'true'
      config:
        description: Path to a file to use for the base configuration object (defaults to "lombiq.markdownlint.json").
        type: string
        default: '.github/actions/markdown-lint/lombiq.markdownlint.json'
      fix:
        description: Whether to fix issues automatically for the rules that support it (any truthy value enables).
        type: string
        default: ''
      globs:
        description: Glob expression(s) of files to lint (newline-delimited).
        type: string
        default: '*.{md,markdown}'
      separator:
        description: String to use as a separator for the "globs" input (defaults to newline).
        type: string
        default: "\n"
      timeout-minutes:
        type: number
        default: 3
        description: Configuration for the timeout-minutes parameter of the workflow.

jobs:
  markdown-linting:
    name: Markdown Linting
    runs-on: ubuntu-22.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}

      # This is a workaround to be able to check submodules too in the repository.
      - name: Stub repo layout
        shell: pwsh
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          Remove-Item .\.git\ -recurse -force
          git init .
          git add .
          git commit -m 'stub commit -- includes submodules'

      - name: Markdown Linting
        uses: Lombiq/GitHub-Actions/.github/actions/markdown-lint@issue/OSOE-744
        with:
          config: ${{ inputs.config }}
          fix: ${{ inputs.fix }}
          globs: ${{ inputs.globs }}
          separator: ${{ inputs.separator }}

      - name: Cancel Workflow on Failure
        if: failure() && inputs.cancel-workflow-on-failure == 'true'
        uses: Lombiq/GitHub-Actions/.github/actions/cancel-workflow@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
