name: Post Pull Request Checks Automation

on:
  workflow_call:
    secrets:
      # We can't access org secrets here so they need to be passed in.
      MERGE_TOKEN:
        required: false
        description: >
          An authentication token, like a personal access token (PAT), that provides write access to the repository and
          can be used to merge the pull request. This is necessary because when a pull request is merged while being
          authenticated with the default GITHUB_TOKEN of a workflow run, then the merge won't trigger other workflows
          (like a build workflow on the target branch). This is an intentional limitation, see:
          https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow.
          Thus, we need to use an alternative authentication token. See
          https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          for info on how to create PATs; you'll need one with the "repo" scope. Check out
          https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
          for instructions on what other tokens you can use.
      JIRA_BASE_URL:
        required: true
        description: >
          Configure as explained under https://github.com/marketplace/actions/jira-login#enviroment-variables. Note that
          it must NOT end with a slash.
      JIRA_USER_EMAIL:
        required: true
        description: Configure as explained under https://github.com/marketplace/actions/jira-login#enviroment-variables.
      JIRA_API_TOKEN:
        required: true
        description: Configure as explained under https://github.com/marketplace/actions/jira-login#enviroment-variables.

    inputs:
      merge-method:
        description: >
          The merge strategy to be used for the auto-merge-pull-request action. See the API documentation for
          "merge_method" for applicable values:
          https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#merge-a-pull-request
        required: false
        type: string
        default: merge
      timeout-minutes:
        required: false
        type: number
        default: 1
        description: Configuration for the timeout-minutes parameter of the workflow.

jobs:
  get_latest_workflow:
    name: Get the latest workflow run number
    runs-on: ubuntu-latest
    outputs:
      latest_run_number: ${{ steps.get_latest_workflow_run_number.outputs.latest_run_number }}
    steps:
      - name: Get the latest workflow run number
        id: get_latest_workflow_run_number
        run: |
          LATEST_RUN_NUMBER=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=push" \
                             | jq '.workflow_runs[0].run_number')
          echo "::set-output name=latest_run_number::$LATEST_RUN_NUMBER"

  post-pull-request-checks-automation:
    runs-on: ubuntu-22.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    if: |
      env.RUN_ONLY_LATEST_WORKFLOW == 'false' || github.run_number == needs.get_latest_workflow.outputs.latest_run_number
    steps:
      - name: Set Merge Token
        shell: pwsh
        env:
          MERGE_TOKEN: ${{ secrets.MERGE_TOKEN }}
        run: |
          $mergeToken = $Env:MERGE_TOKEN ? $Env:MERGE_TOKEN : "${{ secrets.GITHUB_TOKEN }}"
          "MERGE_TOKEN=$mergeToken" >> $Env:GITHUB_ENV

      - name: Automatically Merge Pull Request
        uses: Lombiq/GitHub-Actions/.github/actions/auto-merge-pull-request@dev
        env:
          GITHUB_TOKEN: ${{ env.MERGE_TOKEN }}
        with:
          merge-method: ${{ inputs.merge-method }}

      - name: Automatically Resolve or Done Jira issue
        uses: Lombiq/GitHub-Actions/.github/actions/auto-resolve-done-jira-issue@dev
        env:
          GITHUB_TOKEN: ${{ env.MERGE_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Remove Label
        # v2.0.0
        uses: buildsville/add-remove-label@eeae411a9be2e173f2420e1644514edbecc4e835
        with:
          token: ${{ env.MERGE_TOKEN }}
          labels: merge-and-resolve-jira-issue-if-checks-succeed
          type: remove
