name: Publish to NuGet

on:
  workflow_call:
    inputs:
      cancel-workflow-on-failure:
        description: When set to "true", will cancel the current workflow run with all jobs if this workflow fails.
        required: false
        type: string
        default: "true"
      source:
        required: false
        type: string
        default: https://api.nuget.org/v3/index.json
        description: The NuGet server URL used by the `dotnet nuget push` command's `--source` argument. 
      verbosity:
        required: false
        type: string
        default: minimal
        description: The logging verbosity type used by the `dotnet` command.
      dotnet-version:
        required: false
        type: string
        default: 6.0.x
        description: Version of the .NET SDK to set up.
      timeout-minutes:
        required: false
        type: number
        default: 360
        description: Configuration for the timeout-minutes parameter of the workflow. The 360 is GitHub's default.
      dotnet-pack-ignore-warning:
        required: false
        type: string
        default: ""
        description: >
          Additional warning codes for the `-p:NoWarn=` argument of `dotnet pack`. The items can be 
          separated by any whitespace, including newlines.
      dotnet-pack-include-symbols:
        required: false
        type: string
        default: "true"
        description: If set to "true", a symbol package will be created together with the NuGet package.
      publish-version:
        required: false
        type: string
        default: "USE_GITHUB_REF_NAME"
        description: >
          The desired NuGet package version used for publishing. If not specified, the GITHUB_REF_NAME environment
          variable is used which is suitable if the version is derived from a git tag.
    secrets:
      # We can't access org secrets here so they need to be passed in.
      API_KEY:
        required: true

jobs:
  publish-nuget:
    runs-on: ubuntu-22.04
    # Timeout-minutes is in the matrix only because the config can't be set directly from the inputs, see:
    # https://github.com/actions/runner/issues/1555.
    strategy:
      matrix:
        timeout-minutes: ${{ fromJSON(format('[ {0} ]', inputs.timeout-minutes)) }}
    timeout-minutes: ${{ matrix.timeout-minutes }}
    steps:
    - name: Checkout
      uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev

    - name: Set up .NET
      uses: Lombiq/GitHub-Actions/.github/actions/setup-dotnet@dev
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Publish to NuGet
      uses: Lombiq/GitHub-Actions/.github/actions/publish-nuget@dev
      with:
        source: ${{ inputs.source }}
        verbosity: ${{ inputs.verbosity }}
        dotnet-pack-ignore-warning: ${{ inputs.dotnet-pack-ignore-warning }}
        dotnet-pack-include-symbols: ${{ inputs.dotnet-pack-include-symbols }}
        publish-version: ${{ inputs.publish-version }}
      env:
        API_KEY: ${{ secrets.API_KEY }}

    - name: Cancel Workflow on Failure
      if: failure() && inputs.cancel-workflow-on-failure == 'true'
      uses: Lombiq/GitHub-Actions/.github/actions/cancel-workflow@dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
