name: Reset Azure Environment
# Default values are removed (required: false, type: string)

concurrency:
  group: AzureResetEnvironment

on:
  workflow_call:
    secrets:
      AZURE_APP_SERVICE_RESET_SERVICE_PRINCIPAL:
        required: true
      MAINTENANCE_USER_NAME:
      MAINTENANCE_PASSWORD:
    inputs:
      cancel-workflow-on-failure:
        description: When set to "true", will cancel the current workflow run with all jobs if this workflow fails.
        default: 'false'
      machine-type:
        default: ubuntu-22.04
        description: The name of the type of machine to run the workflow under.
      timeout-minutes:
        type: number
        default: 360
        description: Configuration for the timeout-minutes parameter of the workflow. The 360 is GitHub's default.
      app-name:
        description: What you see at the top of the blade on the Azure Portal. Can contain uppercase letters too.
      destination-slot-name:
        default: Staging
        description: >
          The slot name of the web app you want to reset. What you see at the top of the blade on the Azure Portal, when
          you open the slot, before the app name in parenthesis.
      source-slot-name:
        default: Production
        description: >
          The slot name of the web app you want to reset the destination web app with. What you see at the top of the
          blade on the Azure Portal, when you open the slot, before the app name in parenthesis.
      resource-group-name:
        required: true
        description: Name of the resource group.
      database-connection-string-name:
        default: 'OrchardCore__ConnectionString'
        description: >
          The name of the root SQL Server database connection string configured as application settings in Azure, under both
          the production and staging slots with slot-specific values. This is typically "OrchardCore__ConnectionString",
          and points to the database containing Orchard shell settings, which may also contain the Default tenant's or
          all tenants' databases. This connection string may use a contained user of the given database.
      master-database-connection-string-name:
        default: 'OrchardCore__ConnectionString-master'
        description: >
          The name of the SQL Server database connection string for the master database, configured as application
          settings in Azure, under both the production and staging slots with slot-specific values. This is typically
          "OrchardCore__ConnectionString-master", and points to the SQL Server master database corresponding to the
          database that the database-connection-string-name parameter points to. This elevated access is necessary to
          recreate the staging database and scale it up if necessary.
      storage-connection-string-name:
        default: 'OrchardCore__OrchardCore_Media_Azure__ConnectionString'
        description: >
          The name of the Azure storage account's blob storage connection string, configured as application settings in
          Azure, under both the production and staging slots with slot-specific values. This is typically
          "OrchardCore__OrchardCore_Media_Azure__ConnectionString".
      service-objective-name:
        default: S0
        description: The name of the service objective to scale the database to, e.g. B, S1, S4, P4, P6.
      blob-container-exclude-list:
        default: "@()"
        description: >
          PowerShell string array with the name of the excluded Blob Container(s), e.g. '@("not-media")' or
          '@("not-media", "bad-container")'. The parameter must be a PowerShell string array. When a not empty
          PowerShell string array is provided for "blob-container-include-list", then "blob-container-exclude-list" is
          not taken into consideration.
      blob-container-include-list:
        default: '@("media", "dataprotection")'
        description: >
          PowerShell string array with the name of the included Blob Container(s), e.g. '@("media")' or '@("media",
          "dataprotection)'. The parameter must be a PowerShell string array. When a not empty PowerShell string array
          is provided, "blob-container-exclude-list" is not taken into consideration.
      folder-exclude-list:
        default: '@("RecipeJournal", "`$`$`$ORCHARD`$`$`$.`$`$`$")'
        description: >
          PowerShell string array with the name of the excluded folder(s), e.g. '@("RecipeJournal")' or
          '@("RecipeJournal", "BadFolder")'. The parameter must be a PowerShell string array. When a not empty
          PowerShell string array is provided for "folder-include-list", then "folder-exclude-list" is not taken into
          consideration.
      folder-include-list:
        default: "@()"
        description: >
          PowerShell string array with the name of the included folder(s), e.g. '@("NotRecipeJournal")' or
          '@("NotRecipeJournal", "CoolFolder")'. The parameter must be a PowerShell string array. When a not empty
          PowerShell string array is provided, "folder-exclude-list" is not taken into consideration.
      application-insights-resource-id:
        description: >
          ID of the Application Insights resource that the release annotation for the reset should be added to.
          This can e.g. be looked up on the Azure Portal under the given AI resource's Overview page -> JSON View.
      maintenance-host-name:
        description: >
          The hostname of the Orchard 1-based application that runs a maintenance based on the Multi Tenancy feature
          (https://github.com/Lombiq/Hosting-Multi-Tenancy#writing-maintenance-providers).
      maintenance-batch-size:
        default: '0'
        description: The batch size of the maintenance.

jobs:
  reset-azure-environment:
    runs-on: ${{ inputs.machine-type }}
    name: Reset Azure Environment
    defaults:
      run:
        shell: pwsh
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Login to Azure
        uses: Lombiq/GitHub-Actions/.github/actions/login-to-azure@dev
        env:
          SERVICE_PRINCIPAL: ${{ secrets.AZURE_APP_SERVICE_RESET_SERVICE_PRINCIPAL }}

      - name: Initialize PowerShell modules
        uses: Lombiq/Infrastructure-Scripts/.github/actions/initialize@dev

      - name: Stop Web App Slot
        run: |
          Stop-AzureWebAppSlot `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -WebAppName ${{ inputs.app-name }} `
            -SlotName ${{ inputs.destination-slot-name }}

      - name: Replace Media
        run: |
          Set-AzureWebAppStorageContentFromStorage `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -WebAppName ${{ inputs.app-name }} `
            -SourceSlotName ${{ inputs.source-slot-name }} `
            -DestinationSlotName ${{ inputs.destination-slot-name }} `
            -ConnectionStringName ${{ inputs.storage-connection-string-name }} `
            -ContainerBlackList ${{ inputs.blob-container-exclude-list }} `
            -ContainerWhiteList ${{ inputs.blob-container-include-list }} `
            -FolderBlackList ${{ inputs.folder-exclude-list }} `
            -FolderWhiteList ${{ inputs.folder-include-list }}

      - name: Replace Database
        run: |
          Copy-AzureWebAppSqlDatabase `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -WebAppName ${{ inputs.app-name }}  `
            -SourceSlotName ${{ inputs.source-slot-name }} `
            -DestinationSlotName ${{ inputs.destination-slot-name }} `
            -ConnectionStringName ${{ inputs.database-connection-string-name }} `
            -Force

      - name: Add Destination Contained User to Destination Database
        run: |
          Install-Module sqlserver -AllowClobber -Force
          Add-AzureWebAppSqlDatabaseContainedUser `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -WebAppName ${{ inputs.app-name }} `
            -DatabaseSlotName ${{ inputs.destination-slot-name }} `
            -DatabaseConnectionStringName ${{ inputs.master-database-connection-string-name }} `
            -UserConnectionStringName ${{ inputs.database-connection-string-name }}

      - name: Remove Source Contained User from Destination Database
        run: |
          Remove-AzureWebAppSqlDatabaseContainedUser `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -WebAppName ${{ inputs.app-name }} `
            -DatabaseSlotName ${{ inputs.destination-slot-name }} `
            -UserSlotName ${{ inputs.source-slot-name }} `
            -DatabaseConnectionStringName ${{ inputs.master-database-connection-string-name }} `
            -UserConnectionStringName ${{ inputs.database-connection-string-name }}

      - name: Add Azure Application Insights Release Annotation
        if: ${{ inputs.application-insights-resource-id != '' }}
        uses: Lombiq/GitHub-Actions/.github/actions/add-azure-application-insights-release-annotation@dev
        with:
          release-name: "Reset #${{ github.run_number }} from ${{ inputs.source-slot-name }} to ${{ inputs.destination-slot-name }}"
          application-insights-resource-id: ${{ inputs.application-insights-resource-id }}

      - name: Start Web App Slot
        run: |
          Start-AzureWebAppSlot `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -WebAppName ${{ inputs.app-name }} `
            -SlotName ${{ inputs.destination-slot-name }}

      - name: Test Web App Slot
        run: |
          Test-AzureWebApp `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -WebAppName ${{ inputs.app-name }} `
            -SlotName ${{ inputs.destination-slot-name }}

      - name: Start AfterReplace Maintenance on the Destination Slot
        if: inputs.maintenance-host-name != ''
        run: |
          $maintenanceParameters = @{
            HostName = '${{ inputs.maintenance-host-name }}'
            UserName = '${{ secrets.MAINTENANCE_USER_NAME }}'
            Password = '${{ secrets.MAINTENANCE_PASSWORD }}'
            BatchSize = '${{ inputs.maintenance-batch-size }}'
            MaintenanceName = '${{ inputs.destination-slot-name }}AfterReplace'
          }
          Start-Maintenance @maintenanceParameters

      - name: Scale Database
        run: |
          Set-AzureWebAppSqlDatabaseServiceObjective `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -WebAppName ${{ inputs.app-name }} `
            -SlotName ${{ inputs.destination-slot-name }} `
            -ConnectionStringName ${{ inputs.master-database-connection-string-name }} `
            -ServiceObjectiveName ${{ inputs.service-objective-name }}

      - name: Cancel Workflow on Failure
        if: failure() && inputs.cancel-workflow-on-failure == 'true'
        uses: Lombiq/GitHub-Actions/.github/actions/cancel-workflow@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
