name: Spelling

on:
  workflow_call:
    secrets:
      CHECKOUT_TOKEN:
        required: false
        description: >
          The GitHub token to authenticate checkout. Pass in a GitHub personal access token if authenticated submodules
          are used.

    inputs:
      cancel-workflow-on-failure:
        description: When set to "true", will cancel the current workflow run with all jobs if this workflow fails.
        required: false
        type: string
        default: "true"
      merge-file-excludes:
        description: >
          When set to "true", the "excludes.txt" file's contents in Lombiq.GitHub.Actions will be merged into the one in
          the workspace repository.
        required: false
        type: string
        default: "true"
      merge-ignore-patterns:
        description: >
          When set to "true", the "patterns.txt" file's contents in Lombiq.GitHub.Actions will be merged into the one in
          the workspace repository.
        required: false
        type: string
        default: "true"
      default-dictionary-source-prefixes:
        description: >
          JSON map of prefixes for dictionary URLs, "cspell" is necessary. See
          https://github.com/check-spelling/check-spelling/blob/v0.0.21/action.yml#L67 for current version.
        required: false
        type: string
        default: >
          {
            "lombiq-lgha": "https://raw.githubusercontent.com/Lombiq/GitHub-Actions/issue/OSOE-523/.github/actions/spelling/dictionaries/",
            "cspell": "https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20220816/dictionaries/",
          }
      default-dictionaries:
        description: Space delimited list of URLs (or `prefix:`+path) to additional word lists
        required: false
        type: string
        default: |
          cspell:filetypes/filetypes.txt
          cspell:software-terms/src/software-terms.txt
      additional-dictionary-source-prefixes:
        description: >
          JSON map of prefixes for dictionary URLs, "cspell" is necessary. See
          https://github.com/check-spelling/check-spelling/blob/v0.0.21/action.yml#L67 for current version.
        required: false
        type: string
      additional-dictionaries:
        description: Space delimited list of URLs (or `prefix:`+path) to additional word lists
        required: false
        type: string
      config:
        description: Relative path to the spell-checking configuration folder.
        required: false
        type: string
        default: .github/actions/spelling
      spell-check-this:
        description: >
          Repository with default configuration to use when the workspace repository doesn't have its own configuration. The
          default from Check Spelling is ''.
        required: false
        type: string
        default: Lombiq/GitHub-Actions@issue/OSOE-523

jobs:
  check-spelling:
    name: Check Spelling
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@issue/OSOE-523
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}

      # This is a workaround for the spelling workflow to check submodules too in the repository.
      - name: Stub repo layout
        shell: pwsh
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          Remove-Item .\.git\ -recurse -force
          git init .
          git add .
          git commit -m 'stub commit -- includes submodules'

      - name: Check Spelling
        uses: Lombiq/GitHub-Actions/.github/actions/spelling@issue/OSOE-523
        with:
          merge-file-excludes: ${{ inputs.merge-file-excludes }}
          merge-ignore-patterns: ${{ inputs.merge-ignore-patterns }}
          default-dictionary-source-prefixes: ${{ inputs.default-dictionary-source-prefixes }}
          default-dictionaries: ${{ inputs.default-dictionaries }}
          additional-dictionary-source-prefixes: ${{ inputs.additional-dictionary-source-prefixes }}
          additional-dictionaries: ${{ inputs.additional-dictionaries }}
          config: ${{ inputs.config }}
          spell-check-this: ${{ inputs.spell-check-this }}

      - name: Cancel Workflow on Failure
        if: failure() && inputs.cancel-workflow-on-failure == 'true'
        uses: Lombiq/GitHub-Actions/.github/actions/cancel-workflow@issue/OSOE-523
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
