name: Spelling
# This is the same workflow you'd find in our other submodules. Unlike the rest of the workflows in this repo, this one
# is meant to actually run here, so don't call it from other repos.

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  spelling:
    name: Spelling
    uses: Lombiq/GitHub-Actions/.github/workflows/spelling.yml@issue/OSOE-744
    with:
      additional-dictionaries: |
        cspell:companies/src/companies.txt
      additional-configuration-source-prefixes: >
        {
          "lombiq-lgha": "https://raw.githubusercontent.com/Lombiq/GitHub-Actions/issue/OSOE-744/.github/actions/spelling/"
        }
