name: Swap Azure Web App Slots

on:
  workflow_call:
    secrets:
      AZURE_APP_SERVICE_SWAP_SERVICE_PRINCIPAL:
        required: true
    inputs:
      cancel-workflow-on-failure:
        description: When set to "true", will cancel the current workflow run with all jobs if this workflow fails.
        required: false
        type: string
        default: "false"
      machine-type:
        required: false
        type: string
        default: ubuntu-22.04
        description: The name of the type of machine to run the workflow under.
      timeout-minutes:
        required: false
        type: number
        default: 360
        description: Configuration for the timeout-minutes parameter of the workflow. The 360 is GitHub's default.
      app-name:
        required: true
        type: string
        description: What you see at the top of the blade on the Azure Portal. Can contain uppercase letters too.
      source-slot-name:
        required: false
        type: string
        default: Staging
        description: >
          The slot name of the web app you want to swap the destination slot (of the same web app) with. What you see at
          the top of the blade on the Azure Portal, when you open the slot, before the app name in parenthesis.
      destination-slot-name:
        required: false
        type: string
        default: Production
        description: >
          The slot name of the web app you want to swap with the source slot (of the same web app). What you see at the
          top of the blade on the Azure Portal, when you open the slot, before the app name in parenthesis.
      resource-group-name:
        required: true
        type: string
        description: Name of the resource group.
      application-insights-resource-id:
        required: true
        type: string
        description: >
          ID of the Application Insights resource that the release annotation for the swap should be added to.
          This can e.g. be looked up on the Azure Portal under the given AI resource's Overview page -> JSON View.

jobs:
  swap-azure-web-app-slots:
    runs-on: ${{ inputs.machine-type }}
    name: Swap Azure Web App Slots
    defaults:
      run:
        shell: pwsh
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Login to Azure
        uses: Lombiq/GitHub-Actions/.github/actions/login-to-azure@dev
        env:
          SERVICE_PRINCIPAL: ${{ secrets.AZURE_APP_SERVICE_SWAP_SERVICE_PRINCIPAL }}

      - name: Initialize PowerShell modules
        uses: Lombiq/Infrastructure-Scripts/.github/actions/initialize@dev

      - name: Test Source Web App Slot
        run: |
          Test-AzureWebApp `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -WebAppName ${{ inputs.app-name }} `
            -SlotName ${{ inputs.source-slot-name }}

      - name: Swap Web App Slots
        run: |
          Switch-AzWebAppSlot `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -Name ${{ inputs.app-name }} `
            -SourceSlotName ${{ inputs.source-slot-name }} `
            -DestinationSlotName ${{ inputs.destination-slot-name }}

      - name: Add Azure Application Insights Release Annotation
        uses: Lombiq/GitHub-Actions/.github/actions/add-azure-application-insights-release-annotation@dev
        with:
          application-insights-resource-id: ${{ inputs.application-insights-resource-id }}

      - name: Test Destination Web App Slot
        run: |
          Test-AzureWebApp `
            -ResourceGroupName ${{ inputs.resource-group-name }} `
            -WebAppName ${{ inputs.app-name }} `
            -SlotName ${{ inputs.destination-slot-name }}

      - name: Cancel Workflow on Failure
        if: failure() && inputs.cancel-workflow-on-failure == 'true'
        uses: Lombiq/GitHub-Actions/.github/actions/cancel-workflow@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
