name: Tag and Release LGHA
on:
  push:
    branches:
      - release/*

jobs:
  run:
    name: Update LGHA Refs
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Checkout Repository
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev
        with:
          token: ${{ secrets.TAG_AND_RELEASE }}

      - name: Determine Version Tag Name from Branch Name
        id: determine-tag
        shell: pwsh
        run: |
          $refname = "${{ github.ref_name }}"
          $tagname = $refname -replace 'release/', ''
          $output = "tagname=$tagname"
          Write-Output "output=$output"
          $output >> $env:GITHUB_OUTPUT
      
      - name: Set Ref for GitHub Actions and Workflows
        uses: Lombiq/GitHub-Actions/.github/actions/set-gha-refs@issue/OSOE-735
        with:
          expected-ref: '${{ steps.determine-tag.outputs.tagname }}'

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update called GitHub Actions and Workflows to release version
          tagging_message: ${{ steps.determine-tag.outputs.tagname }}
