name: Validate GHA Refs
on:
  push:
    branches:
      - dev
      - issue/OSOE-517

jobs:
  validate-gha-refs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev

      - name: Verify GHA Workflows/Actions Match Expected Refs
        uses: Lombiq/GitHub-Actions/.github/actions/verify-gha-refs@issue/OSOE-517
