name: Validate GHA Refs
on:
  push:
    branches:
      - dev
  pull_request:
  pull_request_review:
    types: [submitted]
  
jobs:
  check-pr-reviews:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      pull-requests: read
    outputs:
      last-review-approved: ${{ steps.check-pr-reviews.outputs.last-review-approved }}
    steps:
      - name: Check PR Reviews
        id: check-pr-reviews
        uses: Lombiq/GitHub-Actions/.github/actions/check-pull-request-reviews@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-gha-refs:
    needs: check-pr-reviews
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Repository
        if: github.event_name != 'pull_request'
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev

      - name: Get Pull Request File Changes
        id: git-diff
        if: github.event_name == 'pull_request'
        uses: Lombiq/GitHub-Actions/.github/actions/get-changed-files-from-git-diff@dev
        with:
          left-commit: ${{ github.event.pull_request.base.sha }}
          right-commit: ${{ github.sha }}

      - name: Get GHA Item Changes from File Changes
        id: changed-items
        if: github.event_name == 'pull_request'
        uses: Lombiq/GitHub-Actions/.github/actions/get-changed-gha-items@dev
        with:
          file-include-list: '${{ steps.git-diff.outputs.changed-files }}'

      - name: Prefix File Names with Owner/Repo Name
        id: add-prefix
        if: github.event_name == 'pull_request'
        shell: pwsh
        run: |
          $prefix = "${{ github.repository }}"
          $files = ${{ steps.changed-items.outputs.changed-items }}
          $files = $files.ForEach({ Join-Path -Path $prefix -ChildPath $PSItem })
          $output = "prefixed-files=@(" + $($files | Join-String -DoubleQuote -Separator ',') + ")"
          Write-Output "output=$output"
          $output >> $env:GITHUB_OUTPUT

      - name: Determine Expected Ref for GHA Files
        id: determine-ref
        if: github.event_name == 'pull_request'
        shell: pwsh
        run: |
          $headRef = "${{ github.head_ref }}"
          $baseRef = "${{ github.base_ref }}"
          $lastReviewApproved = "${{ needs.check-pr-reviews.outputs.last-review-approved }}"

          # Ternary operator syntax available starting in PowerShell 7.0.
          $expectedRef = ($lastReviewApproved -eq 'True') ? $baseRef : $headRef

          $output = "expected-ref=$expectedRef"
          $output >> $env:GITHUB_OUTPUT

      - name: Verify GHA Items Match Expected Ref (Pull)
        if: github.event_name == 'pull_request' && steps.add-prefix.outputs.prefixed-files != '@()'
        uses: Lombiq/GitHub-Actions/.github/actions/verify-gha-refs@dev
        with:
          called-repo-base-include-list: '${{ steps.add-prefix.outputs.prefixed-files }}'
          expected-ref: ${{ steps.determine-ref.outputs.expected-ref }}

      - name: Verify GHA Items Match Expected Ref (Approved PR)
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
        uses: Lombiq/GitHub-Actions/.github/actions/verify-gha-refs@dev
        with:
          expected-ref: ${{ github.event.pull_request.base.ref }}

      - name: Verify GHA Items Match Expected Ref (Push)
        if: github.event_name == 'push'
        uses: Lombiq/GitHub-Actions/.github/actions/verify-gha-refs@dev
