name: Validate Pull Request

on:
  workflow_call:
    # We can't access org secrets here so they need to be passed in.
    secrets:
      JIRA_BASE_URL:
        required: false
        description: >
          Configure as explained under https://github.com/marketplace/actions/jira-login#enviroment-variables. Note that
          it must NOT end with a slash.
    inputs:
      repository:
        type: string
        required: false
        default: Lombiq/Open-Source-Orchard-Core-Extensions
        description: The parent repository's full name in "{owner}/{repository}" format.
      timeout-minutes:
        required: false
        type: number
        default: 3
        description: Configuration for the timeout-minutes parameter of the workflow.

jobs:
  validate-submodule-pull-request:
    runs-on: ubuntu-22.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Add Jira Issue Code to Pull Request
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: Lombiq/GitHub-Actions/.github/actions/add-jira-issue-code-to-pull-request@issue/OSOE-503
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign issue to PR author
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: Lombiq/GitHub-Actions/.github/actions/assign-issue-to-pr-author@issue/OSOE-503
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure Parent PR Exists
        if: github.event.pull_request != ''
        uses: Lombiq/GitHub-Actions/.github/actions/verify-submodule-pull-request@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.event.pull_request.title }}
          repository: ${{ inputs.repository }}
