name: Validate Reusable Action Workflow References

on:
  workflow_call:
    inputs:
      timeout-minutes:
        required: false
        type: number
        default: 3
        description: Configuration for the timeout-minutes parameter of the workflow.

jobs:
  validate-resusable-action-workflow-refs:
    runs-on: ubuntu-22.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Check for Merge Conflict in PR
        uses: Lombiq/GitHub-Actions/.github/actions/check-reusable-action-workflow-refs-notmatch@dev
        with:
          ref-target: $Env:GITHUB_HEAD_REF
