name: Verify Submodule Pull Request

on:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
        default: Lombiq/Open-Source-Orchard-Core-Extensions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Ensure Parent PR Exists
      uses: Lombiq/GitHub-Actions/.github/actions/verify-submodule-pull-request@dev
      with:
        title: ${{ github.event.pull_request.title }}
