name: Print summary of important configuration
description: Contains .NET, Node.js, and pnpm versions, among others

runs:
  using: "composite"
  steps:
    - name: Write configuration to summary
      shell: pwsh
      run: |
        "### dotnet: $(dotnet --version)" >> $env:GITHUB_STEP_SUMMARY
        "### node  : $(node -v)" >> $env:GITHUB_STEP_SUMMARY
        "### pnpm  : $(pnpm -v)" >> $env:GITHUB_STEP_SUMMARY
